# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84df1d3c995da10f1526cc76219587de58c5522de92fd0a826bff533dba65ac172e03fb4f3856eb3391a9226d014515b07e86d8933dce3a70df0b5dfc2d0bd3d

test:
  secret_key_base: 5739ede1c26f11ea92a1634f8e6f8e5bcf00b635522ae18b27bd233c1fbf3605619624f18f54594fdd842734662d8c36af96257acf4d9c8c5560c23755772fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
